POST http://localhost:8000/stores
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJleHBpcmVzIjoxNzA4NzU1MjczLCJ1c2VySWQiOjF9.aCcV6QoKYWlUGubEcIwuzP6W-qFywYxpD0ysqGkQ4UI

{
  "title": "Test Store",
  "description": "Test description",
  "status": "draft",
  "userId": 1
}